# Generated by Django 4.0.2 on 2022-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city1', models.CharField(max_length=100)),
                ('city2', models.CharField(max_length=100)),
                ('dist', models.FloatField()),
            ],
        ),
    ]
