# Generated by Django 4.0.2 on 2022-02-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('city1', 'city2')},
        ),
    ]
