# Generated by Django 4.0.2 on 2022-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_alter_distance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='dist',
        ),
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
